### ISSUE TITLE
Password protected video

### ISSUE THREAD

**Issue by alx** [Chocobozzz/PeerTube#620]
Hi PeerTube team,

Would it be possible to have password protected video, so they could be shared and only accessed if the visitor has the correct password ?

Thanks,

Alex

**Comment by rigelk** [comment]
Hi @alx ! I guess that's possible - do you have a specific idea of how that would translate for the end user?

It also has a few implications. For instance the comment system would need to be disabled (unless we don't care), as we have no way to federate encrypted messages on the fediverse yet.

**Comment by alx** [comment]
Hi @rigelk , thanks for your answer!

## end user : video publisher

* [x] upload a video
* [ ] in the public/private publishing options, add "private with password" option
* [ ] when "private with password" publishing option selected, add 2 forms to set and confirm a password to access to this video when it'd be published

## end user : visitor

* [x] use video url to access it
* [ ] if the video is published as "private with password", a password form will appear to access to this video

It's an useful option on vimeo to share private video with family members, and I've seen other usecases around this process.

If this issue is an easy target, maybe the comment system part could come later in another issue.

**Comment by Chocobozzz** [comment]
Do we really want to merge the privacy setting (private, unlisted, public) with the password? Maybe some users would want to federate their videos with a password (in unlisted privacy setting for example).

For the comments I think we don't really care for now :)

**Comment by alx** [comment]
Yes, that would be great to have the behavior.

**Comment by novadeviator** [comment]
I'd like to vote and this +1. It would really be great to be able to password-protect some videos. Yes, comments are optional. If they cannot be implemented (or it is hard).

My use case is video documentation of stage productions. I'd love to create a PeerTube instance (I will!) for a small cultural production non-profit where we could share trailers for everyone, but also have option to upload full documentation of shows - these are in 99% not appropriate for general public but more for producers who want to invite a show to their festival (on the other side of the world) and want to see the whole show and we want to share it with them but with a password and maybe even with download 'disabled'.

**Comment by novadeviator** [comment]
Is there any progress on this? Just kindly pinging. It's been almost two years. I would really like to use PeerTube for distribution of public AND private art videos to select audience (your patrons or subscribers for example - Patreon/Bandcamp/mailing-list).

**Comment by rigelk** [comment]
hi @novadeviator - the issue has no "In progress" tag nor any linked commit/pull request, so no progress was made regarding its implementation. Part of why the issue is not yet implemented stems from the complexity not of implementing the simplest iteration of the functionality (yet another privacy mode), but of integrating the password-protection to existing privacy modes. Another reason _might be_ that the plugin API could integrate with the password-protection to allow different ways to check if you can access the content than just a password. All in all, there are multiple stars to align if we want to do this right and not have to re-code the functionality every time we add a potential usage :slightly_smiling_face:

**Comment by novadeviator** [comment]
@rigelk thank you for very iluminating and informative answer. i agree that it is best to think it over well enough first - especially if it's a complex thing - , than to rush it and make it suboptimal or needing too many rewrites.

thank you for your work.

**Comment by GoalTV** [comment]
Would be great to protect from DMCA for Twitch Vods to share only with Subs on discord. Hopefully there will be password protection soon. or even discord intergration for the role to watch video :D

**Comment by ivan386** [comment]
You want hide information about video behind password or/and encrypt video?

**Comment by whyronimus** [comment]
Are there any plans to implement this in Peertube 4.x?

It would be great if Videos, and Livestreams as well, had a "password" option when generating (ability to add it later would be even better). The description and other info should be hidden until password is entered. The password feature could be restricted, so only certain user groups (e.g. admins) could set one.

**Comment by Chocobozzz** [comment]
Hi,

This feature is planned in our 2023 roadmap: https://joinpeertube.org/news/roadmap-v6
If you want to help to fund this feature, you can make a donation on https://support.joinpeertube.org

**Comment by wickloww** [comment]
This issue is fixed in https://github.com/Chocobozzz/PeerTube/pull/5836 :sparkles: 
This feature allows you to password-protect a video.
It also enables the server to manage several passwords. Using the [Rest API](https://docs.joinpeertube.org/api-rest-reference.html), it is therefore possible to use this functionality as a token manager.

**Comment by jfqd** [comment]
@wickloww This is an absolute great feature!

Got it working, but I did not found an api request for adding only one additional password.   Do I really need to query first for all passwords and then add these plus the additional password?

There is a request for deleting only one password by id, why not only add one password to the list of existing passwords for a video? Something like:

```
curl -i -H 'Authorization: Bearer 123456c7f54911186c4c1051f1d951b039f86499' -X PUT \
  https://peertube.example.com/api/v1/videos/42/passwords?password=seriouslongpassword
```

Would be great to have this option! Or do I overlook something?

**Comment by jfqd** [comment]
I fixed it for myself by removing the [Line 76 of passwords.ts](https://github.com/Chocobozzz/PeerTube/blob/develop/server/core/controllers/api/videos/passwords.ts#L76) to not delete all passwords before storing an array of passwords.

The function call to delete all passwords looks like (if anybody else is this situation and not a node developer):

```
await VideoPasswordModel.deleteAllPasswords(videoId, t)
```

**Comment by Chocobozzz** [comment]
@jfqd I created an issue: https://github.com/Chocobozzz/PeerTube/issues/6710

**Comment by jfqd** [comment]
@Chocobozzz Thanks a lot!
