### ISSUE TITLE
Better Moderation Tools

### ISSUE THREAD

**Issue by Nutomic** [Chocobozzz/PeerTube#718]
__NOTE: this meta-issue will be replaced by individual issues for each feature request, as it is much easier to track and document this way. A documentation page will soon replace it to provide an overview of the domain as well as an explanation of PeerTube's current fitness for different moderation situations. Stay tuned!__

At the moment, Peertube's moderation tools try to cover basic needs for all use cases, but you might want to check which are still lacking to see if you feel they are enough for your use case.

## How to contribute

If you think an area is lacking, please create an issue explaining the use cases covered, and why it's important. We should label it as a "Moderation" issue shortly afterwards to better keep track of it.

Note this issue is not immediately updated after each "Moderation" issue's status change.

## Taxonomy

List of principals concerned with moderation tools:

- administrators
- moderators
- users
- external users
- external instances
- visitors

### DMCA-related

Reducing risks of copyright infringement.

- [ ] have an admin-contact form
  - [ ] have a DMCA-template

### Registration verification-related

- [x] email verification at the registration (PR #977)

### Community verification-related

- [x] ban a user (with message)
- [ ] block and hide an actor (issue #1008)
- [ ] admin can force new videos to go through approbation queue (issue #138)
  - [ ] can whitelist users trusted by the admin 
- [ ] admin/video author can force new comments to go through approbation queue (https://github.com/Chocobozzz/PeerTube/issues/898)
  - [ ] can whitelist users trusted by the admin/video author
- [ ] ~warn a user (with message)~
- [ ] ~deactivate a user (with a message)~ Duplicate with ban a user
- [ ] ~list of all the mod actions taken against a user~
- [ ] mods can see all unlisted videos, to make sure they abide by the rules (issue #826 | partially solved | lacking proper UI panel)
- [x] global backlog (issue #826 | PR #837)
- [x] blacklist a video locally (issue #825)
- [x] remove nonsensical reports (issue #895)
- [ ] suspend whole instances (issue #896)
- [ ] have a reporting policy (with a default text, that can be overridden by the admin) and link to it in the report modal for users

### UI tasks

- [x] design a report view (issue #897)
- [ ] redesign the report modal for users
- [ ] design a backlog view (for a user)
- [ ] design a backlog view (for a video)

**Comment by rezonant** [comment]
Could add CAPTCHA support for signup along with email verification as options.

**Comment by XenonFiber** [comment]
A big tool I see missing here is suspension of whole instances. If an instance is incompatible with the COC of yours and/or doesn't deal with abuse well enough, you'd need to constantly keep watch over it's interactions (which becomes impossible fast).

Unfollowing doesn't do more than prevent the videos from being listed. The instance can still follow and comment on yours, including ones that aren't PeerTube. There's nothing to stop a raid on the comments or spam on a large scale.

**Comment by XenonFiber** [comment]
@rigelk Yup, just did!

**Comment by Nutomic** [comment]
Banning a user currently only prevents them from logging in, but doesn't remove any of their videos. I think the ban dialog should include an option to either hide or delete all videos uploaded by the user.

**Comment by Chocobozzz** [comment]
@Nutomic If you want to delete user videos, just delete the user. I think this type of checkbox will be useful when **block and hide an actor** will be implemented (I just edited the first post to add it), so you ban a user with the possibility to hide his content (videos, comments...) too.

**Comment by Nutomic** [comment]
@Chocobozzz If I delete the user, I can't send any message to them (with a reason for the deletion/ban).

**Comment by Chocobozzz** [comment]
@Nutomic You can send an email to hum (it's what we basically do with the ban reason).

**Comment by Nutomic** [comment]
Yes I can send an email manually, but that is much more work. Also, the email comes from a different address, so it won't be clear for the user that it came from the instance admin/mod.

**Comment by Nutomic** [comment]
Some other mod related features that would be useful:
- direct link to go from user profile `https://peertube.social/accounts/*username*` to user update page `https://peertube.social/admin/users/update/*userid*`
- also show email, signup date on the update user page
- option on video page to delete video + send warning or ban user
- search for user by name or email in users list

Also, I don't understand why "warn a user" was striked out in the OP (it is different from banning a user).

**Comment by Chocobozzz** [comment]
Please create separate issue for each feature. I tried to reduce the scope of this issue, that is difficult to track.

**Comment by Nutomic** [comment]
Okay I see, that's gonna be a lot of issues. I will create issues tomorrow (at least some of them).

**Comment by gled-rs** [comment]
The lack of moderation/admin tools starts to be an real issue ( admin of peertube.mastodon.host here ):
- no way to search a specific user in the userlist, to ban or whatever means clicking through 50-60 pages.
- no way to ban a remote user, currently you need to defederate the whole remote instance.
- no 'mod' status that we could give to external people to help with dealing with bad content.
- etc..

Could you consider adding real admin tools more urgently ?

It becomes quite painful to manage an instance now. to the point that I am thinking of either closing regs, disabling upload or just defederating the time for things to be manageable or at worst, keeping the current content and freezing it till it becomes easier to host and manage an instance.

**Comment by rigelk** [comment]
@gled-rs the development schedule has been constrained by the list of features from the crowdfunding, but now that everything from that list is essentially done, moderation tools are coming up next and are the main focus.

**Comment by Chocobozzz** [comment]
> no 'mod' status that we could give to external people to help with dealing with bad content.

You have it: 
![screen_2018-10-05-10 06 00](https://user-images.githubusercontent.com/5180488/46523546-50b4d000-c886-11e8-92dd-cdd57e2e05ff.png)

As @rigelk said, we'll work on these features at the end of the year and in 2019.

**Comment by rigelk** [comment]
@gled-rs I'll take the search implementation (you can follow progress in the issue I created for the occasion: #1197)

**Comment by gled-rs** [comment]
Thank you @Chocobozzz I had not realized it was there yet !

And thank you @rigelk, it is indeed one of the most missing element with mass edit ( mass block, mass change of quotas for users, etc... ).

I appreciate your willingness to take feedback from admins :)

**Comment by scanlime** [comment]
One important issue I haven't seen here so far is how to moderate comments.

• Of course anyone in the fediverse could comment locally, but as an admin I want tools to control which comments are allowed to appear on my instance.

• And as a user I'd want to block other users' comments or block individual comments.

• As an admin or as a video publisher, we need a list of recent comments so that we can see what's ready to moderate and/or reply to.

**Comment by Chocobozzz** [comment]
Closing this meta issue, now every point is tracked by its own issue. Use the [moderation label](https://github.com/Chocobozzz/PeerTube/issues?q=is%3Aissue+is%3Aopen+label%3A%22Component%3A+Moderation+%3Agodmode%3A%22) to track them.
